# Generated by Django 5.0.2 on 2024-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=100000000000000)),
                ('short_url', models.URLField(max_length=100000000000000)),
            ],
        ),
    ]
