# Generated by Django 5.0.2 on 2024-02-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=10000),
        ),
    ]
