# Generated by Django 5.0.2 on 2024-02-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0003_alter_url_short_url_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=100),
        ),
    ]
