# Generated by Django 5.0.2 on 2024-03-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0005_alter_url_short_url_alter_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=1000),
        ),
    ]
